[package]
name = "ureeves-userfaultfd"
version = "0.8.1"
authors = ["The Wasmtime Project Developers"]
edition = "2018"
license = "MIT OR Apache-2.0"
description = "Rust bindings for the Linux userfaultfd functionality"
repository = "https://github.com/bytecodealliance/userfaultfd-rs"
readme = "README.md"

[dependencies]
bitflags = "2.4.0"
cfg-if = "^1.0.0"
libc = "0.2.65"
nix = { version = "0.27", features = ["ioctl"] }
thiserror = "1.0.4"

[dependencies.userfaultfd-sys]
path = "userfaultfd-sys"
package = "ureeves-userfaultfd-sys"
version = "^0.5.0"
default-features = false

[dev-dependencies]
nix = { version = "0.27", features = ["poll", "mman", "feature"] }

[features]
default = ["runtime"]
runtime = ["userfaultfd-sys/runtime"]
static = ["userfaultfd-sys/static"]
linux4_14 = ["userfaultfd-sys/linux4_14", "nix/process"]
linux5_7 = ["userfaultfd-sys/linux5_7"]
